const ADD_PRODUCT = 'ADD_PRODUCT';
const SET_COUNT_PRODUCTS = 'SET_COUNT_PRODUCTS';
const SET_COUNT_TOTAL = 'SET_COUNT_TOTAL';
const CHANGE_COUNT = 'CHANGE_COUNT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';

export {
    ADD_PRODUCT,
    SET_COUNT_PRODUCTS,
    SET_COUNT_TOTAL,
    CHANGE_COUNT,
    DELETE_PRODUCT,
}